version: '3.8'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:15.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: salesdb
    networks:
      - sales-app-network
networks:
  sales-app-network: