create table if not exists payment_security_hash
(
    id bigint generated by default as identity
    primary key,
    order_id       varchar(255),
    hash_code   varchar(255)
);

alter table payment_security_hash
    owner to avnadmin;

