alter table messages
drop constraint fkg15gkrrbt45ogo3udesaofwcf;

drop table if exists rooms_chat;

create table if not exists rooms_chat
(
    id bigint generated by default as identity
    primary key,
    is_seen boolean,
    sender varchar(255) not null,
    receiver varchar(255) not null,
    room_id varchar(255) not null

    );

alter table rooms_chat
    owner to avnadmin;